### ISSUE TITLE
Wrong signature of deleteItem

### ISSUE THREAD

**Issue by hoegertn** [sam-goodwin/typesafe-dynamodb#12]
I think the `deleteItem`call does not have `Item` but `Key` as a field

https://github.com/sam-goodwin/typesafe-dynamodb/blob/main/src/delete-item.ts#L9

**Comment by sam-goodwin** [comment]
Sorry about that - copy/pasted that one late at night ;). Fixed in https://github.com/sam-goodwin/typesafe-dynamodb/pull/14/files

**Comment by sam-goodwin** [comment]
Fixed in `0.0.5`
