### ISSUE TITLE
MetadataBearer missing in UpdateItem and Scan

### ISSUE THREAD

**Issue by bok-at-built** [sam-goodwin/typesafe-dynamodb#31]
See here:
https://github.com/sam-goodwin/typesafe-dynamodb/blob/2ca185f83cbc482b468f74a2b61f116a74206192/src/document-client-v3.ts#L170
https://github.com/sam-goodwin/typesafe-dynamodb/blob/2ca185f83cbc482b468f74a2b61f116a74206192/src/document-client-v3.ts#L197

**Comment by sam-goodwin** [comment]
Thanks for reporting this bug. Fixed in #32. Available in [0.1.9](https://github.com/sam-goodwin/typesafe-dynamodb/releases/tag/v0.1.9)
