### ISSUE TITLE
Incorrect type inference from GetItem command (v3)

### ISSUE THREAD

**Issue by volkanunsal** [sam-goodwin/typesafe-dynamodb#41]
The type of Item appears to be undefined. I expected it to be `IAccount`

<img width="416" alt="Screen Shot 2022-06-19 at 5 40 19 PM" src="https://user-images.githubusercontent.com/151600/174501368-8ee1a1be-450a-4940-a892-01abc632ed2a.png">

Here is the code

```ts
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';

const client1 = new DynamoDBClient({});

export const docClient = DynamoDBDocumentClient.from(
  client1
) as TypeSafeDocumentClientV3<IAccount, 'pk', 'sk'>;

const res1 = await docClient.send(
  new TypedGetItemCommand({
    TableName: 'Account',
    Key: {
      pk: 'ACCOUNT#foo',
      sk: 'ACCOUNT#foo',
    },
  })
);
res1.Item;
```

**Comment by sam-goodwin** [comment]
How is `TypedGetItemCommand` defined?

**Comment by volkanunsal** [comment]
```ts
export const TypedGetItemCommand = TypeSafeGetDocumentCommand<
  IAccount,
  'pk',
  'sk'
>();
```

**Comment by sam-goodwin** [comment]
Hmm, I can't seem to reproduce this error.

![image](https://user-images.githubusercontent.com/38672686/174689726-c0262501-b3d5-4f8a-b5a0-bd0ea691b21b.png)

**Comment by sam-goodwin** [comment]
Tried the same code in a separate package to make sure it works when importing `typesafe-dynamodb` from `node_modules` and it works.

```ts
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient } from "@aws-sdk/lib-dynamodb";
import { TypeSafeDocumentClientV3 } from "typesafe-dynamodb/lib/document-client-v3";
import { TypeSafeGetDocumentCommand } from "typesafe-dynamodb/lib/get-document-command";

const client1 = new DynamoDBClient({});

export interface IAccount {
  pk: string;
  sk: string;
}

export const docClient = DynamoDBDocumentClient.from(
  client1
) as TypeSafeDocumentClientV3<IAccount, "pk", "sk">;

export const TypedGetItemCommand = TypeSafeGetDocumentCommand<
  IAccount,
  "pk",
  "sk"
>();

async function main() {
  const res1 = await docClient.send(
    new TypedGetItemCommand({
      TableName: "Account",
      Key: {
        pk: "ACCOUNT#foo",
        sk: "ACCOUNT#foo",
      },
    })
  );
  res1.Item;
}
```

**Comment by sam-goodwin** [comment]
Got it, now I can repro. Will dig in.

**Comment by sam-goodwin** [comment]
Narrowed down the problem to `Narrow`.

```ts
// is `never` because TS isn't smart enough to detect the overlap
type A = Extract<
  IAccount,
  {
    pk: "ACCOUNT#pk";
    sk: `ACCOUNT#${string}`;
  }
>
```

This may be a limitation of string literal types in typescript.

<img width="256" alt="image" src="https://user-images.githubusercontent.com/38672686/174695962-33a319ce-ddaf-42b3-a14d-80a96683478e.png">

The reason for why `Item` is `undefined` in your example is because `never | undefined` reduces to `undefined`.

**Comment by sam-goodwin** [comment]
I don't think we can workaround this issue. It is not an expected use-case to have hard-coded suffixes in the keys that aren't properly represented in the type (`IAccount`). It will only work if the types are parameterized.

You can see the general problem here - `ACCOUNT#${string}` is not assignable to `ACCOUNT#abc` and therefore narrows to `never`. Maybe TS could be smarter here and realize that `ACCOUNT#${string}` should be narrowed to the literal string `ACCOUNT#abc`. I will cut an issue with the TypeScript team and see what they think.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/38672686/174696899-6a32ca3c-11a1-4615-a0a5-a21276d6f73e.png">

**Comment by volkanunsal** [comment]
Yeah, that is a bummer.

**Comment by sam-goodwin** [comment]
Intersection types do seem to behave better here. 

![image](https://user-images.githubusercontent.com/38672686/174709227-cbdd1bc1-a346-4825-9e89-632c19fa4d4b.jpeg)
