### ISSUE TITLE
Cannot find name 'Simplify'.

### ISSUE THREAD

**Issue by luke-m** [sam-goodwin/typesafe-dynamodb#54]
Hey,

I'm getting this error when trying to build my project. I looked into your source code and it seems like the Simplify type isn't exported and your code references it without an import. How does that work? 

I've tried playing around with the tsconfig, using the one you provide [here](https://github.com/sam-goodwin/typesafe-dynamodb-repro/blob/main/tsconfig.json), but I can't get it to work.

I'm mostly just curious as to why it seems to work in other projects :D I've used this package in one of my projects without a problem before and now I've come back after a while to continue working on the project and this error came up. I don't remember this from before, so I'm extra confused.

Best regards,
Luke

**Comment by sam-goodwin** [comment]
Well, this looks totally broken: https://github.com/sam-goodwin/typesafe-dynamodb/blob/main/src/get-item.ts#L33

Looks like an easy fix.

**Comment by sam-goodwin** [comment]
Sorry for the late reply - got buried in my notifications.

**Comment by sam-goodwin** [comment]
I think this should be fixed in `v0.2.5` - LMK if it works for you.

**Comment by luke-m** [comment]
Works for me, thanks!
